services:
  - type: web
    name: order-book-simulator
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SYMBOL
        value: btcusdt
